Freetype: Use git and update to 2.1.12 release
mesonbuild/wrapdb pull request #364
Opened 2022-04-02 16:31 UTC by satmandu

- This is as per the format in the harfbuzz freetype subproject: https://github.com/harfbuzz/harfbuzz/blob/main/subprojects/freetype2.wrap
- Uses the URL currently used for freetype development at https://gitlab.freedesktop.org/freetype/freetype

2022-04-02 16:47 UTC, xclaesse commented
Our policy for wrapdb is to not use wrap-git and only accept wraps based on released tarball.

2022-04-02 21:17 UTC, satmandu commented
Is this more acceptable?

2022-04-02 21:26 UTC, satmandu commented
(And should a PR update releases.json too?)

2022-04-02 21:46 UTC, jpakkane requested changes

2022-04-02 21:46 UTC, jpakkane commented on subprojects/freetype2.wrap
> +directory = freetype
This should be the directory that the tar file has, so probably `freetype-2.12.0`.

2022-04-02 21:46 UTC, jpakkane commented on subprojects/freetype2.wrap
> +freetype = freetype_dep
FWICT this is not correct. The pkg-config name of Freetype is `freetype2` so this should match that. Just remove this line.

2022-04-02 21:47 UTC, jpakkane commented
> (And should a PR update releases.json too?)

Yes.

2022-04-02 22:44 UTC, satmandu commented
> > (And should a PR update releases.json too?)
> 
> Yes.

I see releases are suffixed with a "-1" or higher.  So I assume this should be '2.12.0-1' ?

2022-04-02 23:10 UTC, xclaesse commented
Exact

2022-04-03 00:04 UTC, satmandu commented
done

2022-04-03 01:40 UTC, eli-schwartz commented
After the suggested review changes, we are back to the original freetype2.wrap file, but with the version number bumped and the hash updated.

Please squash all changes into one commit. Commit message should probably be something like `Freetype: update to 2.1.12 release`

2022-04-03 01:46 UTC, satmandu commented
Adjusted. (Also fixed the title, as we are talking about version 2.12.0...)

2022-04-03 01:59 UTC, eli-schwartz commented
I see upstream actually provides both gz and xz, makes sense to switch to the latter indeed.

2022-04-03 02:20 UTC, eli-schwartz commented
The macOS CI is erroring out by telling you that this update fixes CI there, so you should remove it from the known-broken list.

2022-04-03 02:30 UTC, satmandu commented
Where is that?

2022-04-03 02:32 UTC, eli-schwartz commented
The CI message calls out the string `broken_darwin`, you can find this in the file `ci_config.json`.

2022-04-03 02:34 UTC, satmandu commented
Done.

2022-04-03 02:48 UTC, merged

2022-04-03 02:49 UTC, eli-schwartz commented
Thanks!